spring:
  application:
    name: gateway
  config:
    import: optional:configserver:https://cloud.seoeungi.work
  cloud:
    config:
      fail-fast: true
    gateway:
      routes:
        - id: planverse-dev
          uri: lb://planverse-dev
          predicates:
            - Path=/planverse-dev/**
        - id: planverse-main
          uri: lb://planverse
          predicates:
            - Path=/planverse/**
