server:
  port: 8762
  shutdown: graceful

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:https://config.seoeungi.work
  cloud:
    config:
      fail-fast: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://${spring.security.user.name}:${spring.security.user.password}@eureka.seoeungi.work/eureka
